In [16]:

# Q1.2 - Write a function to generate Gauss Seidel Iteration for a given square matrix. The function should also 
# return the values of 1, ∞ and Frobenius norms of iteration matrix. Generate a random 4 × 4 matrix. Report the 
# Iteration matrix and its norm values returned by the function along with the input matrix.





#import numpy
import numpy as np
from numpy import array,inf
from numpy.linalg import norm 
from scipy.linalg import solve

#generTING RANDOM MATRIX
A = np.random.randint(10, size=(4, 4)) 
# Size of the Matrix is given in the problem statement 4 X 4 

print("The input matrix A\n",(A)) # Array matrix

#AX = B (RHS)
B = np.random.randint(10, size=(4, 1)) 
print("\nThe input matrix B\n",(B)) 



# Cheking diaglonally dominant
def DiagonallyDominant(x):
    abs_x = np.abs(x)
    if np.all( 2*np.diag(abs_x) >= np.sum(abs_x, axis=1)):
        print ('\nMatrix is diagonally dominant')
    else:
        print ('\nMatrix not is diagonally dominant')
    return
DiagonallyDominant(A)


# gauss_seidel
def gauss_seidel(a, b, tolerance=1e-10, max_iterations=10000):
    
    x = np.zeros_like(b, dtype=np.double)
    
    #Iterate
    for k in range(max_iterations):
        
        x2  = x.copy()
        
        #Loop over rows
        for i in range(a.shape[0]):
            x[i] = (b[i] - np.dot(a[i,:i], x[:i]) - np.dot(a[i,(i+1):], x2[(i+1):])) / a[i ,i]
            
        #Break condition
        if np.linalg.norm(x - x2, ord=np.inf) / np.linalg.norm(x, ord=np.inf) < tolerance:
            break
            
    return print("\nItration matrix:\n",x)

gauss_seidel(A, B, tolerance, max_iterations)

#liniear norm
print("\nlinear norm: ", np.linalg.norm(B, ord=1))



# Infinite norm
infintie_norm_B = norm(B,inf)
print("Infinite norm: ",infintie_norm_B)



# Frobenius norm
frobenius_norm_B = norm(B,'fro')
print("Frobenius norm: ",frobenius_norm_B)


The input matrix A
 [[3 5 7 2]
 [8 5 0 9]
 [9 4 7 3]
 [8 5 1 4]]

The input matrix B
 [[9]
 [1]
 [5]
 [9]]

Matrix not is diagonally dominant

Itration matrix:
 [[nan]
 [nan]
 [nan]
 [nan]]

linear norm:  24.0
Infinite norm:  9.0
Frobenius norm:  13.711309200802088
