In [8]:

# Q1.3 - Write a function to generate Gauss Jacobi iteration for a given square matrix. The function should also 
# return the values of 1, ∞ and Frobenius norms of iteration matrix. Generate a random 4 × 4 matrix. Report the 
# Iteration matrix and its norm values returned by the function along with the input matrix.

#(Repeat part (ii) for the Gauss Jacobi iteration)

#import numpy
import numpy as np
from numpy import array,inf
from numpy.linalg import norm 
from scipy.linalg import solve

# Generate Random Matrix

A= np.random.randint(10, size=(4, 4)) 
# Size of the Matrix is given in the problem statement 4 X 4 

print("The input matrix A\n",(A)) # Array matrix

#AX = B (RHS)
B = np.random.randint(10, size=(4, 1)) 
print("\nThe input matrix B\n",(B)) 

# Cheking diaglonally dominant
def DiagonallyDominant(x):
    abs_x = np.abs(x)
    if np.all( 2*np.diag(abs_x) >= np.sum(abs_x, axis=1)):
        print ('\nMatrix is diagonally dominant')
    else:
        print ('\nMatrix not is diagonally dominant')
    return
DiagonallyDominant(A)


def jacobi(a,b,x,n):
    Dig_coeffieints=np.diag(A)
    R=A-np.diagflat(Dig_coeffieints)
    for i in range(n):
        x=(b-np.dot(R,x))/Dig_coeffieints
    return print("\nItration matrix:\n",x)


x = np.ones((4, 4))
N = 25

jacobi(A, B, x, N)


#liniear norm
print("\nlinear norm: ", np.linalg.norm(B, ord=1))



# Infinite norm
infintie_norm_B = norm(B,inf)
print("Infinite norm: ",infintie_norm_B)



# Frobenius norm
frobenius_norm_B = norm(B,'fro')
print("Frobenius norm: ",frobenius_norm_B)


The input matrix A
 [[1 7 3 4]
 [1 3 8 9]
 [3 8 1 7]
 [6 1 6 7]]

The input matrix B
 [[4]
 [6]
 [6]
 [0]]

Matrix not is diagonally dominant

Itration matrix:
 [[-6.04510223e+29 -7.35856304e+17 -6.04510223e+29 -4.85744947e+08]
 [-7.28196895e+29 -8.86417227e+17 -7.28196895e+29 -5.85131480e+08]
 [-7.32306413e+29 -8.91419648e+17 -7.32306413e+29 -5.88433621e+08]
 [-5.55722770e+29 -6.76468467e+17 -5.55722770e+29 -4.46542535e+08]]

linear norm:  16.0
Infinite norm:  6.0
Frobenius norm:  9.38083151964686
