In [18]:
import numpy as np
from numpy import linalg


a1 = np.random.rand(5) 
print('a1:', a1)
a2 = np.random.rand(5)
print('a2:', a2)
a3 = np.random.rand(5) 
print('a3:', a3)
a4 = np.random.rand(5)
print('a4:', a4)
a5 = np.random.rand(5) 
print('a5:', a5) 
print("\n")

matrx = np.array ([a1,a2,a3,a4,a5])

no_of_rows = matrx.shape[0] 
no_of_columns = matrx.shape[1]
 

def vecotrs_dependency(matrix,row_nb): 
    rank_of_matrix = np.linalg.matrix_rank(matrix)

    print('Row Count:',row_nb) 
    print('Matrix Rank:',rank_of_matrix)
    if rank_of_matrix < row_nb:
        print('Given vectors are Lineraly Dependent')
        print('No of independent vector:', rank_of_matrix)
        print('No of Dependent vector:', row_nb - rank_of_matrix)
    else:
        print('Random vectors are Lineraly Independent')

                   
vecotrs_dependency(matrx,no_of_rows)


a1: [0.18618047 0.05536574 0.75022814 0.22910135 0.03636089]
a2: [0.69339279 0.65877889 0.1746191  0.17922132 0.89183015]
a3: [0.87753514 0.82204964 0.18684105 0.94808251 0.39267524]
a4: [0.41281925 0.79685668 0.02631613 0.16998769 0.98228162]
a5: [0.08885851 0.75382554 0.75899982 0.58788158 0.50905655]


Row Count: 5
Matrix Rank: 5
Random vectors are Lineraly Independent


In [19]:

def gram_schmdt(mtrx):

    n = mtrx.shape[1] 
    for i in range(n):
        for j in range(i):
            mtrx[:, i] -= (np.dot(mtrx[:, j], mtrx[:, i]) * mtrx[:, j])
            mtrx[:, i] = (mtrx[:, i] / np.linalg.norm(mtrx[:, i])) 
        return mtrx

print('a1:', a1)
print('a2:', a2)
print('a3:', a3)
print('a4:', a4)
print('a5:', a5) 
print("\n")

o_vec = np.stack([a1,a2,a3,a4,a5], axis = -1)

print('Matrix of a1,a2,a3,a4,a5 vectors stored as the columns for Gram-Schmidt')
print("\n")

print(o_vec) 
print("\n")

print('Gram-Schmidt Algorithm solved Matrix') 
print("\n")
print(gram_schmdt(o_vec)) 
print("\n")
def vec_list (matrix_name, index_no):
    return matrix_name[:,index_no]


print('Vectors q1, q2, q3, q4, q5 from Gram-Schmidt Algorithm ')
print('\n')
q1 = vec_list(o_vec,0)
q2 = vec_list(o_vec,1) 
q3 = vec_list(o_vec,2) 
q4 = vec_list(o_vec,3) 
q5 = vec_list(o_vec,4)

print('q1:', vec_list(o_vec,0)) 
print('q2:', vec_list(o_vec,1)) 
print('q3:', vec_list(o_vec,2))
print('q4:', vec_list(o_vec,3)) 
print('q5:', vec_list(o_vec,4))


a1: [0.18618047 0.05536574 0.75022814 0.22910135 0.03636089]
a2: [0.69339279 0.65877889 0.1746191  0.17922132 0.89183015]
a3: [0.87753514 0.82204964 0.18684105 0.94808251 0.39267524]
a4: [0.41281925 0.79685668 0.02631613 0.16998769 0.98228162]
a5: [0.08885851 0.75382554 0.75899982 0.58788158 0.50905655]


Matrix of a1,a2,a3,a4,a5 vectors stored as the columns for Gram-Schmidt


[[0.18618047 0.69339279 0.87753514 0.41281925 0.08885851]
 [0.05536574 0.65877889 0.82204964 0.79685668 0.75382554]
 [0.75022814 0.1746191  0.18684105 0.02631613 0.75899982]
 [0.22910135 0.17922132 0.94808251 0.16998769 0.58788158]
 [0.03636089 0.89183015 0.39267524 0.98228162 0.50905655]]


Gram-Schmidt Algorithm solved Matrix


[[0.18618047 0.69339279 0.87753514 0.41281925 0.08885851]
 [0.05536574 0.65877889 0.82204964 0.79685668 0.75382554]
 [0.75022814 0.1746191  0.18684105 0.02631613 0.75899982]
 [0.22910135 0.17922132 0.94808251 0.16998769 0.58788158]
 [0.03636089 0.89183015 0.39267524 0.98228162 0.5090565

In [26]:
print('q1:', q1)
print('q2:', q2)
print('q3:', q3)
print('q4:', q4)
print('q5:', q5) 
print("\n")

Q = np.stack([q1,q2,q3,q4,q5], axis = -1)
print('Matrix B = QTQ') 
print('\n')
B = np.dot(np.transpose(Q), Q) 
print(B)

q1: [0.18618047 0.05536574 0.75022814 0.22910135 0.03636089]
q2: [0.69339279 0.65877889 0.1746191  0.17922132 0.89183015]
q3: [0.87753514 0.82204964 0.18684105 0.94808251 0.39267524]
q4: [0.41281925 0.79685668 0.02631613 0.16998769 0.98228162]
q5: [0.08885851 0.75382554 0.75899982 0.58788158 0.50905655]


Matrix B = QTQ


[[0.65438033 0.37006172 0.58055171 0.21538158 0.78089706]
 [0.37006172 1.77275632 1.70276772 1.72228734 1.25010696]
 [0.58055171 1.70276772 2.53379739 1.5691161  1.59672494]
 [0.21538158 1.72228734 1.5691161  1.79986585 1.25731689]
 [0.78089706 1.25010696 1.59672494 1.25731689 1.75697282]]


#4. write a code to calculate the value of |B-I5|
#deliverable code and display of value generated

In [27]:
M = np.linalg.norm(B - np.identity(5), 'fro')
print ('value of lB - I5lF: ', M)

value of lB - I5lF:  5.880833701542822
