In [20]:

# Q1.1 - Write a function to check whether a given square matrix is diagonally dominant. Test the function on a randomly
# generated 4 × 4 matrix.Deliverable(s) : Code that performs the check and the results obtained for the matrix 

import numpy as np

A = np.random.randint(10, size=(4, 4)) 
# Size of the Matrix is given in the problem statement 4 X 4 

print("The input matrix A\n",(A)) #Print Array (matrix)
print("\nShape: ",A.shape) #Print shape of the array

# Cheking diaglonally dominant
def DiagonallyDominant(x):
    abs_x = np.abs(x)
    if np.all( 2*np.diag(abs_x) >= np.sum(abs_x, axis=1)):
        print ('\nMatrix is diagonally dominant')
    else:
        print ('\nMatrix not is diagonally dominant')
    return
DiagonallyDominant(A)


The input matrix A
 [[3 2 9 8]
 [6 2 7 4]
 [0 9 2 2]
 [5 9 4 8]]

Shape:  (4, 4)

Matrix not is diagonally dominant
